SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE `__CORE_DB_NAME__`.`tenants`;
LOAD DATA LOCAL INFILE '__PATH__/tenants.csv'
INTO TABLE `__CORE_DB_NAME__`.`tenants`
CHARACTER SET UTF8
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

TRUNCATE TABLE `__CORE_DB_NAME__`.`tenant_access_roles`;
LOAD DATA LOCAL INFILE '__PATH__/tenantAccessRoles.csv'
INTO TABLE `__CORE_DB_NAME__`.`tenant_access_roles`
CHARACTER SET UTF8
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

TRUNCATE TABLE `__CORE_DB_NAME__`.`tenant_access_resources`;
LOAD DATA LOCAL INFILE '__PATH__/tenantAccessResources.csv'
INTO TABLE `__CORE_DB_NAME__`.`tenant_access_resources`
CHARACTER SET UTF8
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

TRUNCATE TABLE `__CORE_DB_NAME__`.`tenant_access_permissions`;
LOAD DATA LOCAL INFILE '__PATH__/tenantAccessPermissions.csv'
INTO TABLE `__CORE_DB_NAME__`.`tenant_access_permissions`
CHARACTER SET UTF8
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

SET FOREIGN_KEY_CHECKS = 1;
