SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE `__CORE_DB_NAME__`.`agents`;
LOAD DATA LOCAL INFILE '__PATH__/agents.csv'
INTO TABLE `__CORE_DB_NAME__`.`agents`
CHARACTER SET UTF8
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

TRUNCATE TABLE `__CORE_DB_NAME__`.`cloud_users`;
LOAD DATA LOCAL INFILE '__PATH__/cloudUsers.csv'
INTO TABLE `__CORE_DB_NAME__`.`cloud_users`
CHARACTER SET UTF8
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

TRUNCATE TABLE `__CORE_DB_NAME__`.`prospect_users`;
LOAD DATA LOCAL INFILE '__PATH__/prospectUsers.csv'
INTO TABLE `__CORE_DB_NAME__`.`prospect_users`
CHARACTER SET UTF8
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

TRUNCATE TABLE `__CORE_DB_NAME__`.`tenants`;
LOAD DATA LOCAL INFILE '__PATH__/tenants.csv'
INTO TABLE `__CORE_DB_NAME__`.`tenants`
CHARACTER SET UTF8
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

TRUNCATE TABLE `__CORE_DB_NAME__`.`prospect_tenants`;
LOAD DATA LOCAL INFILE '__PATH__/prospectTenants.csv'
INTO TABLE `__CORE_DB_NAME__`.`prospect_tenants`
CHARACTER SET UTF8
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

TRUNCATE TABLE `__CORE_DB_NAME__`.`tenant_connections`;
LOAD DATA LOCAL INFILE '__PATH__/tenantConnections.csv'
INTO TABLE `__CORE_DB_NAME__`.`tenant_connections`
CHARACTER SET UTF8
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

TRUNCATE TABLE `__CORE_DB_NAME__`.`tenant_organizations`;
LOAD DATA LOCAL INFILE '__PATH__/tenantOrganizations.csv'
INTO TABLE `__CORE_DB_NAME__`.`tenant_organizations`
CHARACTER SET UTF8
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

TRUNCATE TABLE `__CORE_DB_NAME__`.`tenant_members`;
LOAD DATA LOCAL INFILE '__PATH__/tenantMembers.csv'
INTO TABLE `__CORE_DB_NAME__`.`tenant_members`
CHARACTER SET UTF8
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

TRUNCATE TABLE `__CORE_DB_NAME__`.`tenant_access_roles`;
LOAD DATA LOCAL INFILE '__PATH__/tenantAccessRoles.csv'
INTO TABLE `__CORE_DB_NAME__`.`tenant_access_roles`
CHARACTER SET UTF8
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

TRUNCATE TABLE `__CORE_DB_NAME__`.`tenant_access_role_assignments`;
LOAD DATA LOCAL INFILE '__PATH__/tenantAccessRoleAssignments.csv'
INTO TABLE `__CORE_DB_NAME__`.`tenant_access_role_assignments`
CHARACTER SET UTF8
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

TRUNCATE TABLE `__CORE_DB_NAME__`.`tenant_access_resources`;
LOAD DATA LOCAL INFILE '__PATH__/tenantAccessResources.csv'
INTO TABLE `__CORE_DB_NAME__`.`tenant_access_resources`
CHARACTER SET UTF8
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

TRUNCATE TABLE `__CORE_DB_NAME__`.`tenant_access_permissions`;
LOAD DATA LOCAL INFILE '__PATH__/tenantAccessPermissions.csv'
INTO TABLE `__CORE_DB_NAME__`.`tenant_access_permissions`
CHARACTER SET UTF8
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

TRUNCATE TABLE `__CORE_DB_NAME__`.`password_resets`;
LOAD DATA LOCAL INFILE '__PATH__/passwordResets.csv'
INTO TABLE `__CORE_DB_NAME__`.`password_resets`
CHARACTER SET UTF8
COLUMNS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

SET FOREIGN_KEY_CHECKS = 1;
